on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - id: setup-r
        uses: r-lib/actions/setup-r@v2

      - name: Restore renv environment
        run: |
          R -q -e 'options(Ncpus = 2); install.packages("renv", repos = "cloud.r-project.org"); renv::restore()'

      - id: check-leanification
        run: |
          library(mlr3)
          lrn("regr.rpart")$train
        shell: Rscript {0}


