on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Restore renv environment
        run: |
          R -q -e 'options(Ncpus = 2); install.packages("renv", repos = "cloud.r-project.org"); renv::restore()'

      - name: Leanification works when installing "normally"
        run: |
          cd ~
          Rscript -e 'install.packages("mlr3"); library(mlr3); lrn("classif.rpart")$train'
