on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - id: setup-r
        uses: r-lib/actions/setup-r@v2

      - id: setup-mlr3
        run: |
          install.packages("mlr3")
        shell: Rscript {0}

      - id: check-leanification
        run: |
          library(mlr3)
          lrn("regr.rpart")$train
        shell: Rscript {0}



